name       : qt5-websockets
version    : 5.13.0
release    : 15
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.0/submodules/qtwebsockets-everywhere-src-5.13.0.tar.xz : f941dd44f6e16041a25723c1b70ce9e28910c630509da0044ecb9fdda28a6e34
license    :
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Websockets Module
description: |
    WebSocket is a web-based protocol designed to enable two-way communication between a client application and a remote host. It enables the two entities to send data back and forth if the initial handshake succeeds. WebSocket is the solution for applications that struggle to get real-time data feeds with less network latency and minimum data exchange.
    The Qt WebSockets module provides C++ and QML interfaces that enable Qt applications to act as a server that can process WebSocket requests, or a client that can consume data received from the server, or both.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtwebsockets.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
